## =========================
# LOCAL SDK OVERRIDES
# =========================
sdk:
  security:
    enabled: true
    method-security-enabled: false
    cors:
      enabled: false

  # =========================
  # LOCAL LOGGING OVERRIDES
  # =========================
  logging:
    structured:
      enabled: true
      auto-configure-format: false

logging:
  structured:
    format:
      console: ""
